gradboost_pv/app.py
gradboost_pv/inference/run.py

method to save to a database
Fixes #7 
It has not yet, TODO should be running locally and check it wourls

add method to save to a database

---

configs/default_production_model.yaml
gradboost_pv/inference/data_feeds.py

Round to nearest 30 mins upwards and localise to UTC
Fixes #
-

round inference time up to nearest 1/2 hour.

---

Dockerfile
gradboost_pv/app.py

Fix for write to database
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

Add default configs

---

README.md
gradboost_pv/models/training.py

Fill out readme with answers to questions.
Fixes #12

first draft of readme docs

---

gradboost_pv/app.py
gradboost_pv/inference/models.py

add some logging
Fixes #
CI tests

Add logging config

---

tests/inference/test_app.py
tests/inference/test_s3.py

Ski failing tests for the moment
Keep them in, as we should fix them soon. Just need to give CI access to AWS
#24 for the other tests ive made an issue

Skip tests

---

gradboost_pv/app.py
gradboost_pv/inference/data_feeds.py

Get forecast to prediction next SP, this is done by moving the inference time
ran locally

Adjust inference time

---

configs/default_production_model.yaml
gradboost_pv/app.py
gradboost_pv/inference/data_feeds.py

Update to 30 hours, and use zarr.
It may run out of memory when resampling national data to 1 hourly
CI and ran locally,

Update zarr and 30 hours

---

configs/default_production_model.yaml
gradboost_pv/app.py

add wdir10 to NWP parameters
Fixes #
CI tests
Ran locally

add wdir10

---

gradboost_pv/inference/data_feeds.py
gradboost_pv/models/s3.py
requirements.txt

Add memory usage
Fixes #
CI test

add memory usage

---

experiments/002_gsp_lags/readme.md

Add exp by adding more GSP lags, it didnt make to much difference so decided not to add
CI tests

add GSP lags

---

gradboost_pv/app.py
gradboost_pv/save.py
requirements.txt
tests/inference/test_save.py

Upgrade dm to save to forecast_value_latest with model id
Save all forecast_value_latest
Fixes #
Normal ci tests

nowcasting_datamodel==1.2.3

---

requirements.txt

update to dm 1.2.5
Fixes #
CI tests
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

nowcasting_datamodel==1.2.5

---

gradboost_pv/save.py
tests/inference/test_save.py

save to forecast_value_seven_days aswell
Fixes #
Added to tests, and normal tests

also save to last seven days

---

gradboost_pv/models/s3.py
requirements.txt
tests/utils/test_model_features.py

make bucket name flexible on env, ready for production
CI tests

make bucket name flexible on env

---

gradboost_pv/save.py
requirements.txt
tests/inference/conftest.py
tests/inference/test_save.py

- add adjuster to save method
- remove custom save, and use the general one
CI test

update save method

---

requirements.txt

Update, so saves to latest_table
Update to latest dm, fixes bug when saving to latest table

nowcasting_datamodel==1.3.9

---

experiments/010_pv/readme.md

Look at the differences PVlive data makes
Fixes #
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

add results for using PVlive and not

---

configs/default_production_model.yaml

On live upgrade to incldue hours 30 to 36. This is becasue we are pulling more NWP data now
- CI test
- run locally

add extra horizons

---

requirements.txt

Update date model, so no nans in the `adjust_mw`
CI tests

nowcasting_datamodel==1.4.1

---

gradboost_pv/save.py
requirements.txt
tests/inference/test_save.py

Fix for bug with gsp config name. This was to do with this change - https://github.com/openclimatefix/ocf_datapipes/pull/212
I've just pinned it before this change to check it works
added this for reference later https://github.com/openclimatefix/uk-pv-national-xg/issues/92
- CI test
- run locally, and check plevels are in db

ocf_datapipes==1.2.41 and fic for plevels

---

gradboost_pv/inference/models.py

Fix #94
Fixes #94 
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_

Change scaling to relative

---

requirements.txt

This means it will clear the forecast_latest table on save

Bump datamodel version to 1.5.6

---

requirements.txt

Upgrade datamodel, so forecast(historic=True) gets saved correctly
Fixes #
CI tests

nowcasting_datamodel==1.5.8

---

experiments/009_probablistic/readme.md

Adds monthly error and pinball loss plots for production national XG models on the train/test set.
Fixes #
N/A

Add seasonal error results

---

Dockerfile

https://github.com/openclimatefix/ocf-infrastructure/issues/373
Normal CI tests

Update Dockerfile - python312

---

configs/default_production_datafeed.yaml
gradboost_pv/inference/data_feeds.py
requirements.txt

Reduce memory by reduce to variables we need when loading from NWP
fix tests too, by pinning to pydantic==1.10.10
linked with https://github.com/openclimatefix/nwp-consumer/pull/115
fixed #111 
CI tests

Reduce memory

---

.github/workflows/test-pytest.yml
gradboost_pv/inference/data_feeds.py
gradboost_pv/inference/run.py
gradboost_pv/preprocessing/pretrained.py
requirements.txt
tests/conftest.py
tests/inference/test_app.py

Update to use nowcasting-datamodel 1.5.41
Had to pin requests<2.32.0 - https://github.com/psf/requests/issues/6707
CI tests

upgrade to datamodel 1.5.41

---

configs/default_production_model.yaml

- update gsp variables
CI tests

gsp_installed_capacity_name: nominal_capacity_mwp

---

.github/workflows/test-pytest.yml
Dockerfile

install standard xgboost
CI tests

install latest xgboost

---

requirements.txt

nowcasting_datamodel==1.5.43
CI tests

nowcasting_datamodel==1.5.43

---

gradboost_pv/inference/data_feeds.py

- rename MO UKV variables
- this is for https://github.com/openclimatefix/nwp-consumer/pull/226
build off https://github.com/openclimatefix/uk-pvnet-app/pull/284

rename UKV variables

---

requirements.txt

Pin zarr to <3, needed for #124 
CI tests

pin zarr to 2.18.4
